---
#to install self certificate
- include_vars: user.yml

#configure winrm script to path 
- name: configurating winrm path 
  win_file: 
    path: "{{ config_path }}"
    state: directory

- name: creating configuration winrm path
  template:
    src: "ConfigureRemotingForAnsible.ps1"
    dest: "{{ config_path }}"

#create temporal folder for powershell script 
- name: Creating temporal ps1 execution folder
  win_file:
    path: "{{ config['install']['configPath'] }}{{ config['install']['configTempFolder'] }}"
    state: directory
 # when: ansible_windows_domain != "{{ cert['cert_name']}}"

# creates template for the script for it execution 
- name: creating windows self-certificate in config path
  template: 
    src: "New-SelfSignedCertificateEx.ps1.j2" 
    dest: "{{ config['install']['configPath'] }}{{ config['install']['configTempFolder'] }}{{ config['install']['ps1certificate'] }}"

# windows upgrade powershell to 3.0  in config path
- name: windows upgrade powershell to 3.0  in config path
  template: 
    src: "Powershell2.0_upgrade_to_3.0.ps1.j2" 
    dest: "{{ config['install']['configPath'] }}{{ config['install']['configTempFolder'] }}{{ config['install']['ps1powershellupgrade'] }}"

#upgrade powershell to 3.0 if required
- name: upgrade powershell to 3.0 if required
  win_shell: "{{ config['install']['configPath'] }}{{ config['install']['configTempFolder'] }}{{ config['install']['ps1powershellupgrade'] }}"

#start self certificate execution 
- name: Starting ps1 self certificate execution
  win_shell: "{{ config['install']['configPath'] }}{{ config['install']['configTempFolder'] }}{{ config['install']['ps1certificate'] }}"    


#configure installation path for  vmtools to ensure variable application
- name:  creating path for vmtools variables application 
  template: 
    src: "vmtools.ps1.j2" 
    dest: "{{ config['install']['configPath'] }}{{ config['install']['configTempFolder'] }}{{ config['install']['ps1vmtools'] }}"

#installing vmtools for variables 
- name: 
  win_shell: "{{ config['install']['configPath'] }}{{ config['install']['configTempFolder'] }}{{ config['install']['ps1vmtools'] }}"

- name: test wirm connectivity
  win_ping:
    win_pin: 
    
#delete temporal self certificate ps1 file
- name: Deleteing temporal self certificate ps1 execution folder
  win_file:
    path: "{{ config['install']['configPath'] }}{{ config['install']['configTempFolder'] }}"
    state: absent
  when: true != {{ config['debug'] }}


  
#- name: Reboot windows machine
#  win_reboot:
